### ISSUE TITLE
OpenCV.js

### ISSUE THREAD

**Issue by dkurt** [SimpleVlad/freeCodeCamp#2]
Here is integration status:

| sample | code | test | description |
|---|---|---|---|
| bgr2gray| <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/1</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/9</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/12</li></ul> |
| blur | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/7</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/9</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/13</li></ul> |
| contrast | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/5</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/9</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/14</li></ul> |
| resize | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/8</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/9</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/15</li></ul> |
| rotate | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/10</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/11</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/16</li></ul> |
| addWeighted | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/3</li></ul>| <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/3</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/3</li></ul> |
| contours | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/4</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/9</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/17</li></ul> |
| drawings | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/6</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/9</li></ul> | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/18</li></ul> |
| inpaint | <ul><li>[x] https://github.com/SimpleVlad/freeCodeCamp/pull/19</li></ul> | <ul><li>[ ] https://github.com/SimpleVlad/freeCodeCamp/pull/20</li></ul> | <ul><li>[ ] https://github.com/SimpleVlad/freeCodeCamp/pull/20</li></ul> |

**Comment by SimpleVlad** [comment]
We may add graph "in progress" to keep track of what we are working on

**Comment by ieliz** [comment]
I think we can mark "add weighted" and "inpaint" as "Completed" in "code" column.

**Comment by dkurt** [comment]
@ilbalance, When we merge it
